### ISSUE TITLE
Fix compatability issues in V10

### ISSUE THREAD

**Issue by etriebe** [etriebe/dnd-randomizer#17]
`Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1245:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:6166:14)
    at get data [as data] (commons.js:6066:24)
    at hasProperty (commons.js:1685:41)
    at Object.replaceActorArtwork [as fn] (caeora.mjs:55:53)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12424:47)
    at async ClientDatabaseBackend._createDocuments (foundry.js:12337:22)
    at async Actor5e.createDocuments (commons.js:5631:23)
    at async Actor5e.create (commons.js:5754:23)
    at async EncCreature.getActor (encounter.js:253:7)
    at async Encounter.loadActors (encounter.js:152:7)
    at async Encounter.spawn (encounter.js:157:5)
logCompatibilityWarning @ commons.js:1256
_logV10CompatibilityWarning @ commons.js:6166
get data @ commons.js:6066
hasProperty @ commons.js:1685
replaceActorArtwork @ caeora.mjs:55
#call @ foundry.js:688
call @ foundry.js:670
_preCreateDocumentArray @ foundry.js:12424
await in _preCreateDocumentArray (async)
_createDocuments @ foundry.js:12337
create @ commons.js:6262
await in create (async)
createDocuments @ commons.js:5631
create @ commons.js:5754
importFromCompendium @ foundry.js:14120
await in importFromCompendium (async)
getActor @ encounter.js:253
loadActors @ encounter.js:152
spawn @ encounter.js:157
(anonymous) @ dialog.js:210
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
commons.js:1256 
        
       Error: You are accessing Actor5e#data which has been migrated to Actor5e#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1245:19)
    at Actor5e._logDataFieldMigration (commons.js:6155:14)
    at Object.get (commons.js:6119:18)
    at hasProperty (commons.js:1685:41)
    at Object.replaceActorArtwork [as fn] (caeora.mjs:55:53)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12424:47)
    at async ClientDatabaseBackend._createDocuments (foundry.js:12337:22)
    at async Actor5e.createDocuments (commons.js:5631:23)
    at async Actor5e.create (commons.js:5754:23)
    at async EncCreature.getActor (encounter.js:253:7)
    at async Encounter.loadActors (encounter.js:152:7)
    at async Encounter.spawn (encounter.js:157:5)
logCompatibilityWarning @ commons.js:1256
_logDataFieldMigration @ commons.js:6155
get @ commons.js:6119
hasProperty @ commons.js:1685
replaceActorArtwork @ caeora.mjs:55
#call @ foundry.js:688
call @ foundry.js:670
_preCreateDocumentArray @ foundry.js:12424
await in _preCreateDocumentArray (async)
_createDocuments @ foundry.js:12337
create @ commons.js:6262
await in create (async)
createDocuments @ commons.js:5631
create @ commons.js:5754
importFromCompendium @ foundry.js:14120
await in importFromCompendium (async)
getActor @ encounter.js:253
loadActors @ encounter.js:152
spawn @ encounter.js:157
(anonymous) @ dialog.js:210
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
caeora.mjs:57 Star-SpawnofCthulhu
commons.js:1256 
        
       Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1245:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:6166:14)
    at get data [as data] (commons.js:6066:24)
    at getProperty (commons.js:1707:41)
    at Object.replaceActorArtwork [as fn] (caeora.mjs:58:23)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12424:47)
    at async ClientDatabaseBackend._createDocuments (foundry.js:12337:22)
    at async Actor5e.createDocuments (commons.js:5631:23)
    at async Actor5e.create (commons.js:5754:23)
    at async EncCreature.getActor (encounter.js:253:7)
    at async Encounter.loadActors (encounter.js:152:7)
    at async Encounter.spawn (encounter.js:157:5)
logCompatibilityWarning @ commons.js:1256
_logV10CompatibilityWarning @ commons.js:6166
get data @ commons.js:6066
getProperty @ commons.js:1707
replaceActorArtwork @ caeora.mjs:58
#call @ foundry.js:688
call @ foundry.js:670
_preCreateDocumentArray @ foundry.js:12424
await in _preCreateDocumentArray (async)
_createDocuments @ foundry.js:12337
create @ commons.js:6262
await in create (async)
createDocuments @ commons.js:5631
create @ commons.js:5754
importFromCompendium @ foundry.js:14120
await in importFromCompendium (async)
getActor @ encounter.js:253
loadActors @ encounter.js:152
spawn @ encounter.js:157
(anonymous) @ dialog.js:210
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
commons.js:1256 
        
       Error: You are accessing Actor5e#data which has been migrated to Actor5e#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1245:19)
    at Actor5e._logDataFieldMigration (commons.js:6155:14)
    at Object.get (commons.js:6119:18)
    at getProperty (commons.js:1707:41)
    at Object.replaceActorArtwork [as fn] (caeora.mjs:58:23)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12424:47)
    at async ClientDatabaseBackend._createDocuments (foundry.js:12337:22)
    at async Actor5e.createDocuments (commons.js:5631:23)
    at async Actor5e.create (commons.js:5754:23)
    at async EncCreature.getActor (encounter.js:253:7)
    at async Encounter.loadActors (encounter.js:152:7)
    at async Encounter.spawn (encounter.js:157:5)`

**Comment by etriebe** [comment]
Caused by Caeora.
