### ISSUE TITLE
So many errors

### ISSUE THREAD

**Issue by Nuku** [etriebe/dnd-randomizer#25]
populateMonstersFromCompendiums @ localmodule.js:276
localmodule.js:275 TypeError: Cannot read properties of undefined (reading 'creatureType')
    at eval (eval at getSystemVariableForObject (FoundryUtils.js:43:14), <anonymous>:1:16)
    at FoundryUtils.getSystemVariableForObject (FoundryUtils.js:43:14)
    at ActorUtils.getCreatureTypeForActor (ActorUtils.js:12:44)
    at new NPCActorPf2e (NPCActorPf2e.js:8:38)
    at ActorUtils.getActorObject (ActorUtils.js:55:16)
    at SFLocalHelpers.populateMonstersFromCompendiums (localmodule.js:256:42)
    at async Promise.all (index 1)
    at async SFLocalHelpers.populateObjectsFromCompendiums (localmodule.js:63:9)
    at async HTMLButtonElement.<anonymous> (dialog.js:300:5)
populateMonstersFromCompendiums @ localmodule.js:275
localmodule.js:276 Actor id DM5js1XSiuiPAf3t, name White Dracolisk failed to get added.

--

It is showing this, for a lot of things, in the console as I'm trying to get an encounter.

**Comment by etriebe** [comment]
You might need to DM me some information to log into the world. This error
doesn't happen to me when generating an encounter.

**Comment by etriebe** [comment]
Also, did you force a reindexing of the compendiums? My best guess is an
old index.

**Comment by Nuku** [comment]
![image](https://user-images.githubusercontent.com/886729/214456731-2048a8c8-7a9a-4cf7-b682-93012f4355ab.png)
I have bestiary 1, 2, and 3 checked. PF2E

**Comment by etriebe** [comment]
Ah, pf2e. That's almost certainly what it is. I'll take a look.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by etriebe** [comment]
Fixed! Also fixed actor links, which were broken too. :)
