### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Nuku** [etriebe/dnd-randomizer#40]
![image](https://user-images.githubusercontent.com/886729/226503743-6ea05523-288e-4429-b7ef-b1c2b4982099.png)
Does nothing.
![image](https://user-images.githubusercontent.com/886729/226503768-412c8f88-81df-46ed-bc41-c6d8e4cb5a19.png)
twirls forever...

I have selected compendiums.

**Comment by etriebe** [comment]
What does F12 say?

**Comment by Nuku** [comment]
Click first to see any buttons.
![image](https://user-images.githubusercontent.com/886729/226505242-302cd383-604b-48fd-b86a-63481f6eb172.png)
Click compendiums inside stochcastic
CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(12), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(8), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(5), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(8), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(16), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(11), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(20), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(116), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(8), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(0), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(8), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(8), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(11), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(11), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(11), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(1), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(4), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(8), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(15), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(9), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(12), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(6), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(38), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(1), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(34), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(11), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(18), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(6), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(45), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(111), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(2), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(45), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(21), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(49), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(92), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(291), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(49), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(40), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(42), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(262), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(4184), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(375), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(131), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(319), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(33), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(430), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(23), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(42) {'4D2KBtexWXa6oUMR' => ConditionPF2e, '1wQY3JYyhMYeeV2G' => ConditionPF2e, '3uh1r86TzbQvosxv' => ConditionPF2e, '6dNUvdb1dhToNDj3' => ConditionPF2e, '6uEgoh53GbXuHpTF' => ConditionPF2e, …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(240), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(267), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(2) {'i35dpZFI7jZcRoBo' => SpellPF2e, '6dDtGIUerazSHIOu' => SpellPF2e, …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(227), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(3979), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(65), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(523), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(22), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(341), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(39), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(36), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(341), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(48), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(42), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(17), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(18), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(14), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(162), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(18), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(87), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(80), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(278), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(254), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(331), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(13), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(27), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(365), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(373), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(468), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(235), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(97), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(24), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(99), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(63), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(20), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(5), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(42), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(22), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(16), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(81), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(53), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(141), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(24), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(168), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(19), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(195), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(116), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(9), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(187), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(129), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(112), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(56), #indexedFields: Set(5), …}
compendium.js:49 CompendiumCollection(0) {invalidDocumentIds: Set(0), apps: Array(1), metadata: {…}, index: Collection(1), #indexedFields: Set(5), …}
text.min.mjs:8 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
t.measureFont @ text.min.mjs:8
t.measureText @ text.min.mjs:8
r.updateText @ text.min.mjs:8
r.updateTransform @ text.min.mjs:8
e.updateTransform @ display.min.mjs:8
e.updateTransform @ display.min.mjs:8
e.updateTransform @ display.min.mjs:8
e.updateTransform @ display.min.mjs:8
e.updateTransform @ display.min.mjs:8
e.updateTransform @ display.min.mjs:8
r.render @ core.min.mjs:8
e.render @ app.min.mjs:8
t.emit @ ticker.min.mjs:8
e.update @ ticker.min.mjs:8
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
requestAnimationFrame (async)
_tick @ ticker.min.mjs:8
foundry.js:3133 Foundry VTT | Synchronized official game time in 51ms

---

Click force reindex, Skipping indexing compendium world.tails-of-the-city-ancestry because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.actionspf2e because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.ancestries because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.ancestryfeatures because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.backgrounds because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.classes because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.classfeatures because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.familiar-abilities because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.feats-srd because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.heritages because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.spells-srd because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.bestiary-effects because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.boons-and-curses because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.conditionitems because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.campaign-effects because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.equipment-effects because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.other-effects because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.feat-effects because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.pathfinder-society-boons because it wasn't selected
localmodule.js:186 Skipping indexing compendium pf2e.spell-effects because it wasn't selected
localmodule.js:287 Skipping indexing compendium world.baileywiki-maps-actors because it wasn't selected
localmodule.js:287 Skipping indexing compendium pf2e.abomination-vaults-bestiary because it wasn't selected
localmodule.js:287 Skipping indexing compendium pf2e.age-of-ashes-bestiary because it wasn't selected
---
Click generate encounter
bestiary because it wasn't selected
EncounterUtilsPf2e.js:164 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'itemtype')
[Detected 1 package: dnd-randomizer]
    at EncounterUtilsPf2e.getPF2EItemLootForEncounter (EncounterUtilsPf2e.js:164:43)
    at EncounterUtilsPf2e.getPF2ELootForEncounter (EncounterUtilsPf2e.js:91:50)
    at EncounterUtilsPf2e.createEncounterPf2e (EncounterUtilsPf2e.js:59:52)
    at SFLocalHelpers.createEncounters (localmodule.js:732:55)
    at HTMLButtonElement.<anonymous> (dialog.js:302:50)
getPF2EItemLootForEncounter @ EncounterUtilsPf2e.js:164
getPF2ELootForEncounter @ EncounterUtilsPf2e.js:91
createEncounterPf2e @ EncounterUtilsPf2e.js:59
createEncounters @ localmodule.js:732
(anonymous) @ dialog.js:302

**Comment by etriebe** [comment]
I believe this is because of my work to try and speed things up and switch to promises vs await/async. Looking...

**Comment by etriebe** [comment]
@Nuku Let me know if this isn't fixed for you!
